
//ACTION FOR API
export const FETCH_PRODUCT_REQUEST="FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCES="FETCH_PRODUCT_SUCCES"
export const FETCH_PRODUCT_FAILURE="FETCH_PRODUCT_FAILURE";


//ACTION FOR CART
export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";
export const CHECKOUT="CHECKOUT"